name: release
on:
  push:
    tags:
      - "*"
permissions:
  contents: read
jobs:
  publish-to-pypi:
    name: publish-to-pypi
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - uses: actions/setup-python@v5
        name: install-python
        with:
          python-version: 3.12
      - name: install-deps
        run: |
          pip install -U setuptools wheel build
      - name: build
        shell: bash
        run: |
          python -m build
      - uses: actions/upload-artifact@v4
        with:
          path: ./dist/qiskit*
      - name: Publish package to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1