name: Test Windows

on:
  push:
    branches:
      - main
      - 'stable/**'
  pull_request:
    branches:
      - main
      - 'stable/**'
  schedule:
    - cron: '0 1 * * *'

jobs:
  tests:
    runs-on: windows-latest
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          python -m venv test-job
          .\test-job\Scripts\activate
          python -m pip install -U pip setuptools wheel tox
          python -m pip install -U -e .
          pip check
      - name: Run Tests
        run: |
          .\test-job\Scripts\activate
          tox -epy312
